# Device: USB Expert Mouse - 3 button mouse with wheel
# Button 1 = click (code 273), Button 2 = wheel down, Button 3 = wheel up
dev: /dev/input/by-id/usb-1c4f_USB_Expert_Mouse-event-mouse [273,EV_REL/REL_WHEEL=-1,EV_REL/REL_WHEEL=1]

# Press escape twice
1: xdotool key --repeat 2 --delay 100 Escape

# Mouse wheel events
2: xdotool click --repeat 2 --delay 0 5
3: xdotool click --repeat 2 --delay 0 4
